#!/usr/bin/env bash
set -euo pipefail

RUN_OUTPUT_DIR="${RUN_OUTPUT_DIR:-results/phase15_mechanism_seal_specificity}"
SEAL_OUTPUT="${SEAL_OUTPUT:-results/phase15_vpref_projection/mechanism_seal_specificity.csv}"
MODEL="${MODEL:-Qwen/Qwen2.5-3B-Instruct}"
ARTIFACT_DIR="${ARTIFACT_DIR:-artifacts/vpref_projection}"
BENIGN_FILE="${BENIGN_FILE:-data/alpaca_cleaned_train.jsonl}"
LAYERS="${LAYERS:-24,28,32,35}"
KR="${KR:-1 4}"
EVAL_LIMIT="${EVAL_LIMIT:-128}"
DIRECTION_LIMIT="${DIRECTION_LIMIT:-256}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"
JUDGE_MAX_NEW_TOKENS="${JUDGE_MAX_NEW_TOKENS:-16}"
NULL_DIRECTIONS="${NULL_DIRECTIONS:-200}"
CONTROL_DIRECTIONS="${CONTROL_DIRECTIONS:-4}"
CONTROL_MIN_GROUP="${CONTROL_MIN_GROUP:-16}"
ACTIVATION_CONTROL_DIRECTIONS="${ACTIVATION_CONTROL_DIRECTIONS:-2}"
ACTIVATION_CONTROL_QUANTILE="${ACTIVATION_CONTROL_QUANTILE:-0.25}"
PROJECTION_NEIGHBOR_RADIUS="${PROJECTION_NEIGHBOR_RADIUS:-4}"
RUN_VALIDATION="${RUN_VALIDATION:-0}"

OUTPUT_DIR="$RUN_OUTPUT_DIR" \
MODEL="$MODEL" \
ARTIFACT_DIR="$ARTIFACT_DIR" \
BENIGN_FILE="$BENIGN_FILE" \
LAYERS="$LAYERS" \
KR="$KR" \
EVAL_LIMIT="$EVAL_LIMIT" \
DIRECTION_LIMIT="$DIRECTION_LIMIT" \
MAX_NEW_TOKENS="$MAX_NEW_TOKENS" \
JUDGE_MAX_NEW_TOKENS="$JUDGE_MAX_NEW_TOKENS" \
NULL_DIRECTIONS="$NULL_DIRECTIONS" \
CONTROL_DIRECTIONS="$CONTROL_DIRECTIONS" \
CONTROL_MIN_GROUP="$CONTROL_MIN_GROUP" \
ACTIVATION_CONTROL_DIRECTIONS="$ACTIVATION_CONTROL_DIRECTIONS" \
ACTIVATION_CONTROL_QUANTILE="$ACTIVATION_CONTROL_QUANTILE" \
PROJECTION_NEIGHBOR_RADIUS="$PROJECTION_NEIGHBOR_RADIUS" \
RUN_VALIDATION="$RUN_VALIDATION" \
bash scripts/phase15_vpref_projection.sh

mkdir -p "$(dirname "$SEAL_OUTPUT")"
cp "$RUN_OUTPUT_DIR/vpref_specificity.csv" "$SEAL_OUTPUT"
cp "$RUN_OUTPUT_DIR/vpref_control_directions.csv" "${SEAL_OUTPUT%.csv}_controls.csv"
cp "$RUN_OUTPUT_DIR/vpref_specificity_decision.json" "${SEAL_OUTPUT%.csv}_decision.json"
echo "[mechanism-seal] wrote $SEAL_OUTPUT"
echo "[mechanism-seal] wrote ${SEAL_OUTPUT%.csv}_controls.csv"
echo "[mechanism-seal] wrote ${SEAL_OUTPUT%.csv}_decision.json"
