#!/usr/bin/env bash
set -euo pipefail

MODE="${MODE:-merge}"
MODEL="${MODEL:-Qwen/Qwen2.5-3B-Instruct}"
OUTPUT_DIR="${OUTPUT_DIR:-results/phase2_oracle_hs_and_coverage}"
SHARD_DIR="${SHARD_DIR:-$OUTPUT_DIR/coverage_shards}"
SOLVE_ARTIFACT="${SOLVE_ARTIFACT:-artifacts/phase2_oracle_hs_and_coverage/remar_solve.pt}"
ARTIFACT_DIR="${ARTIFACT_DIR:-artifacts/vpref_projection}"
MARGIN_DIR="${MARGIN_DIR:-results/phase15_margin_calib}"
LAYERS="${LAYERS:-24,28,32}"
EVAL_DATASET="${EVAL_DATASET:-advbench}"
EVAL_LIMIT="${EVAL_LIMIT:-128}"
ADVBENCH_EVAL_OFFSET="${ADVBENCH_EVAL_OFFSET:-128}"
OOD_EVAL_OFFSET="${OOD_EVAL_OFFSET:-0}"
DECODE_K="${DECODE_K:-32}"
EPSILON="${EPSILON:-0.5}"
ETA="${ETA:-1.0}"
FIT_LIMIT="${FIT_LIMIT:-128}"
ADVBENCH_FIT_OFFSET="${ADVBENCH_FIT_OFFSET:-0}"
BENIGN_FIT_OFFSET="${BENIGN_FIT_OFFSET:-0}"
BENIGN_FIT_LIMIT="${BENIGN_FIT_LIMIT:-128}"
TARGET_MARGIN="${TARGET_MARGIN:-20}"
LAMBDA_BENIGN="${LAMBDA_BENIGN:-20}"
RIDGE_MU="${RIDGE_MU:-0.01}"
DELTA_MAX="${DELTA_MAX:-50}"
MAX_LENGTH="${MAX_LENGTH:-512}"
CALIB_MAX_LENGTH="${CALIB_MAX_LENGTH:-256}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"
RESPONSE_PPL_THRESHOLD="${RESPONSE_PPL_THRESHOLD:-100}"
JUDGE_MAX_NEW_TOKENS="${JUDGE_MAX_NEW_TOKENS:-16}"
CONDITIONAL_MIN_GAP="${CONDITIONAL_MIN_GAP:-1.0}"
TEMPORAL_DROP_THRESHOLD="${TEMPORAL_DROP_THRESHOLD:-0.20}"
TEMPORAL_CONTRAST_THRESHOLD="${TEMPORAL_CONTRAST_THRESHOLD:-0.10}"
MIN_OUTCOME_N="${MIN_OUTCOME_N:-20}"
SEED="${SEED:-0}"
LOCAL_FILES_ONLY="${LOCAL_FILES_ONLY:-1}"
BENIGN_FILE="${BENIGN_FILE:-data/alpaca_cleaned_train.jsonl}"
HARMBENCH_CONFIG="${HARMBENCH_CONFIG:-standard}"

mkdir -p "$OUTPUT_DIR" "$SHARD_DIR" "$(dirname "$SOLVE_ARTIFACT")"

args=(
  --mode "$MODE"
  --model "$MODEL"
  --output-dir "$OUTPUT_DIR"
  --shard-dir "$SHARD_DIR"
  --solve-artifact "$SOLVE_ARTIFACT"
  --artifact-dir "$ARTIFACT_DIR"
  --margin-dir "$MARGIN_DIR"
  --layers "$LAYERS"
  --eval-dataset "$EVAL_DATASET"
  --eval-limit "$EVAL_LIMIT"
  --advbench-eval-offset "$ADVBENCH_EVAL_OFFSET"
  --ood-eval-offset "$OOD_EVAL_OFFSET"
  --decode-k "$DECODE_K"
  --epsilon "$EPSILON"
  --eta "$ETA"
  --fit-limit "$FIT_LIMIT"
  --advbench-fit-offset "$ADVBENCH_FIT_OFFSET"
  --benign-fit-offset "$BENIGN_FIT_OFFSET"
  --benign-fit-limit "$BENIGN_FIT_LIMIT"
  --target-margin "$TARGET_MARGIN"
  --lambda-benign "$LAMBDA_BENIGN"
  --ridge-mu "$RIDGE_MU"
  --delta-max "$DELTA_MAX"
  --max-length "$MAX_LENGTH"
  --calib-max-length "$CALIB_MAX_LENGTH"
  --max-new-tokens "$MAX_NEW_TOKENS"
  --response-ppl-threshold "$RESPONSE_PPL_THRESHOLD"
  --judge-max-new-tokens "$JUDGE_MAX_NEW_TOKENS"
  --conditional-min-gap "$CONDITIONAL_MIN_GAP"
  --temporal-drop-threshold "$TEMPORAL_DROP_THRESHOLD"
  --temporal-contrast-threshold "$TEMPORAL_CONTRAST_THRESHOLD"
  --min-outcome-n "$MIN_OUTCOME_N"
  --seed "$SEED"
  --harmbench-config "$HARMBENCH_CONFIG"
)

if [[ -n "${JUDGE_MODEL:-}" ]]; then args+=(--judge-model "$JUDGE_MODEL"); fi
if [[ -n "$BENIGN_FILE" ]]; then args+=(--benign-file "$BENIGN_FILE"); fi
if [[ "$LOCAL_FILES_ONLY" == "1" ]]; then args+=(--local-files-only); fi

python -m casafety.remar_coverage_diag "${args[@]}"
